# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import logo
import serial
from PyQt5.QtWidgets import QApplication, QMainWindow



from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(320, 460)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(320, 460))
        Form.setMaximumSize(QtCore.QSize(320, 460))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/ll.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(15, 11, 280, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/logo/logo.png"))
        self.label.setObjectName("label")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(215, 188, 80, 50))
        self.pushButton_7.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_7.setMaximumSize(QtCore.QSize(80, 50))
        self.pushButton_7.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:1px groove gray;border-radius:10px;padding:1px 4px;border-style: outset;}\n"
"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\n"
"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}")
        self.pushButton_7.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/logo/arrow-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setEnabled(True)
        self.pushButton_10.setGeometry(QtCore.QRect(118, 245, 80, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_10.setMaximumSize(QtCore.QSize(80, 50))
        self.pushButton_10.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:1px groove gray;border-radius:10px;padding:1px 4px;border-style: outset;}\n"
"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\n"
"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}")
        self.pushButton_10.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/logo/arrow-down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(15, 188, 80, 50))
        self.pushButton_11.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_11.setMaximumSize(QtCore.QSize(80, 50))
        self.pushButton_11.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:1px groove gray;border-radius:10px;padding:1px 4px;border-style: outset;}\n"
"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\n"
"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}")
        self.pushButton_11.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/logo/arrow-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon3)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(118, 131, 80, 50))
        self.pushButton_9.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_9.setMaximumSize(QtCore.QSize(80, 50))
        self.pushButton_9.setStatusTip("")
        self.pushButton_9.setWhatsThis("")
        self.pushButton_9.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:1px groove gray;border-radius:10px;padding:1px 4px;border-style: outset;}\n"
"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\n"
"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}")
        self.pushButton_9.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/logo/arrow-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon4)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(15, 302, 80, 50))
        self.pushButton_6.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_6.setMaximumSize(QtCore.QSize(80, 50))
        self.pushButton_6.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:1px groove gray;border-radius:10px;padding:1px 4px;border-style: outset;}\n"
"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\n"
"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(215, 302, 80, 50))
        self.pushButton_2.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_2.setMaximumSize(QtCore.QSize(80, 50))
        self.pushButton_2.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:1px groove gray;border-radius:10px;padding:1px 4px;border-style: outset;}\n"
"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\n"
"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(15, 380, 80, 50))
        self.pushButton_3.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_3.setMaximumSize(QtCore.QSize(80, 50))
        self.pushButton_3.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:1px groove gray;border-radius:10px;padding:1px 4px;border-style: outset;}\n"
"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\n"
"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(215, 380, 80, 50))
        self.pushButton_4.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_4.setMaximumSize(QtCore.QSize(80, 50))
        self.pushButton_4.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:1px groove gray;border-radius:10px;padding:1px 4px;border-style: outset;}\n"
"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\n"
"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}")
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Form)
        self.pushButton_9.pressed.connect(self.uup)
        self.pushButton_7.pressed.connect(self.rri)
        self.pushButton_11.pressed.connect(self.lle)
        self.pushButton_10.pressed.connect(self.ddo)
        self.pushButton_6.pressed.connect(self.ffa)
        self.pushButton_2.pressed.connect(self.ffb)
        self.pushButton_3.pressed.connect(self.iia)
        self.pushButton_4.pressed.connect(self.iib)
        self.pushButton_9.released.connect(self.st)
        self.pushButton_11.released.connect(self.st)
        self.pushButton_7.released.connect(self.st)
        self.pushButton_10.released.connect(self.st)
        self.pushButton_6.released.connect(self.st)
        self.pushButton_2.released.connect(self.st)
        self.pushButton_3.released.connect(self.st)
        self.pushButton_4.released.connect(self.st)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ElectricVideoAdapter"))
        self.pushButton_7.setToolTip(_translate("Form", "Right"))
        self.pushButton_7.setShortcut(_translate("Form", "Right"))
        self.pushButton_10.setToolTip(_translate("Form", "Down"))
        self.pushButton_10.setShortcut(_translate("Form", "Down"))
        self.pushButton_11.setToolTip(_translate("Form", "Left"))
        self.pushButton_11.setShortcut(_translate("Form", "Left"))
        self.pushButton_9.setToolTip(_translate("Form", "Up"))
        self.pushButton_9.setShortcut(_translate("Form", "Up"))
        self.pushButton_6.setToolTip(_translate("Form", "Focus-"))
        self.pushButton_6.setText(_translate("Form", "F-"))
        self.pushButton_6.setShortcut(_translate("Form", "F"))
        self.pushButton_2.setToolTip(_translate("Form", "Focus+"))
        self.pushButton_2.setText(_translate("Form", "F+"))
        self.pushButton_2.setShortcut(_translate("Form", "G"))
        self.pushButton_3.setToolTip(_translate("Form", "Iris-"))
        self.pushButton_3.setText(_translate("Form", "I-"))
        self.pushButton_3.setShortcut(_translate("Form", "I"))
        self.pushButton_4.setToolTip(_translate("Form", "Iris+"))
        self.pushButton_4.setText(_translate("Form", "I+"))
        self.pushButton_4.setShortcut(_translate("Form", "O"))

    def st(self):
        d = bytes.fromhex('00')
        s.write(d)

    def ffa(self):
        d = bytes.fromhex('56')
        s.write(d)

    def ffb(self):
        d = bytes.fromhex('65')
        s.write(d)

    def iia(self):
        d = bytes.fromhex('34')
        s.write(d)

    def iib(self):
        d = bytes.fromhex('43')
        s.write(d)

    def uup(self):
       d = bytes.fromhex('12')
       s.write(d)

    def ddo(self):
        d = bytes.fromhex('21')
        s.write(d)

    def lle(self):
       d = bytes.fromhex('78')
       s.write(d)

    def rri(self):
        d = bytes.fromhex('87')
        s.write(d)



if __name__ == '__main__':
    #s = serial.Serial("COM2", 9600, timeout=0.5)
    s = serial.Serial("/dev/tty.usbserial-1710", 9600, timeout=0.5)
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_Form()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
